### ISSUE TITLE
add support for addresses had never transacted

### ISSUE THREAD

**Issue by timmeh4242** [eoscafe/eoskeyio#2]
i'm not fully caught up on the technicalities of eos and the transition but i'd like to better understand this - to me even though the snapshot has occurred tokens are not destroyed and with a signature you can always prove ownership.

personally i'd be interested in participating in a solution for the users who were caught in the very, very small minority on this. if a human can use a machine to scan an address and see that it was not mapped at snapshot time, there should be a technical solution here.

**Comment by dskvr** [comment]
That's not how it works.

**Comment by timmeh4242** [comment]
i know that's not how it works, that's why i opened the issue - it doesn't necessarily need to be a part of this tool, but while 0.3% is a small percentage it's still a large number of people who are left out. i'm not sure this is the forum to open the discussion, if not i'd love to be pointed in the right direction.

my understanding is that those tokens were included in the genesis snapshot so that they could be claimed at a later date via some form of arbitration (ie, via a smart contract / oracle, or manual kyc). if they were not included we'd need another solution, ie inflation or other means.
